### ISSUE TITLE
Adding/Replacing Images

### ISSUE THREAD

**Issue by quantyst** [LeKoArts/gatsby-starter-portfolio-cara#1]
I'm trying to change the images in the starter to images of my own, but it's not working. I was just trying to do it quick and dirty so I made sure everything matched up: name, resolution, file extension. Tried reloading $ npm run develop, now the whole thing doesn't load, besides the background color loads for some reason.  

Ok, paths in /d/ for example don't match, let's just make a new project, run $ gatsby new etcetc. Before I do $ npm run develop for the first time, I replace the images in /src/imageswith my own images. 1200x1200, project_1.jpg etc. Still doesn't work. 

I'm sure this is just something simple I'm overlooking because I'm being dumb, but I was just wondering how I can fix this. How can I replace the stock photos with photos of my own?

**Comment by LeKoArts** [comment]
Try this:
- Delete your .cache folder and public folder
- Replace the images with same name and file extension
- Run develop

The images should also be replaced if you run develop and then change the image

**Comment by quantyst** [comment]
Thank you for your quick response, I really appreciate your help. Because I can't get it working in any project folder other than the original, I'm worried about permanently messing it up. So I made a copy of it. In one copy, I did what you said and deleted those folders, but localhost:8000 still loaded a blank screen with just the background color. So, trying to eliminate variables, I just copied the original, working folder again. Without changing anything, I tried running it, and I get the same thing, blank screen. Except, this time, I get 

> GraphQL Error Unknown field `file` on type `RootQueryType`

and also

>success extract queries from components — 0.100 s
⠁ (node:6976) DeprecationWarning: Passing lineNumber and colNumber is deprecated to @babel/code-frame. Please use `codeFrameColumns`.

which I also don't get in the original. Is there something wrong being that the original is set to the original file path somewhere? If that's the case, why didn't it work when I deleted the .cache and public like you mentioned, and reran run develop? I just don't understand why the project works in one folder, but doesn't work in an identical copy, the only thing I can think of is that the copies have a different name root folder, obviously.

**Comment by LeKoArts** [comment]
https://github.com/LeKoArts/gatsby-starter-portfolio-cara/blob/master/gatsby-config.js#L18
This is defining the folder for the images.

https://github.com/LeKoArts/gatsby-starter-portfolio-cara/blob/master/src/pages/index.jsx#L325
Here are the names defined. The size shouldn't matter by the way, they get resized automatically.

Do you need more information?

**Comment by quantyst** [comment]
Oh ok, after some more testing I understand now, thank you so much.

**Comment by LeKoArts** [comment]
Can I close this issue? :)
