### ISSUE TITLE
SEO - Text friendly?

### ISSUE THREAD

**Issue by hirako2000** [LekoArts/gatsby-starter-portfolio-cara#10]
Hi, Awesome work with the 4 gatsby sites!

Is there a way to make the output search engine friendly? currently no text is shown until the JS kicks in.
I assume Gatsby's advantage is to build static html files, that are SEO friendly.(Server Side Rendering on build)

thanks

**Comment by LekoArts** [comment]
Gatsby is SEO friendly and I didn’t change its default behavior. Do a `curl` of your site and you'll see the full HTML. A „View source“ is misleading here as the Service Worker will load the content if it’s installed.

**Comment by hirako2000** [comment]
thanks for your quick response @LekoArts , meta data is seen fine. It's the body content that is not.

e.g `curl portfolio-cara.netlify.com | grep English` 
shows nothing.
