### ISSUE TITLE
There was an error trying to load the config "tailwind" for the macro imported from "tailwind.macro.

### ISSUE THREAD

**Issue by mcronin03** [LekoArts/gatsby-starter-portfolio-cara#108]
I'm trying to deploy my site to Netlify, but I am getting this error:  There was an error trying to load the config "tailwind" for the macro imported from "tailwind.macro. Please see the error thrown for more information.

Here is the repository I am deploying from.  I pretty much have only changed the src file.
https://github.com/mcronin03/HackHershey-2019-Website

I also tried redownloading the starter as described in the readme and swapping in my src file, but I am getting the same error.

Thanks!

**Comment by ronniesong0809** [comment]
According to 
https://github.com/LekoArts/gatsby-starter-portfolio-cara/blob/868b24c685f82903f97181ea516c36596547b2f4/config/website.js#L1
make sure run `npm install --save-dev babel-plugin-macros tailwind.macro` to install babel-plugin-tailwind-components beside from your gatsby directory.

**Comment by LekoArts** [comment]
The starter switched to using a theme, the error shouldn't occur with the new setup. Unfortunately I can't give support for the older versions anymore.
