### ISSUE TITLE
Demo website is broken in production

### ISSUE THREAD

**Issue by cluk3** [LekoArts/gatsby-starter-portfolio-cara#119]
It only shows a black screen.
In the console there are 2 equal errors:
`Uncaught Invariant Violation: Minified React error #321;`
I tried on desktop chrome and Safari and mobile Chrome, and it's the same everywhere.
Running it locally with `gatsby develop` works fine, so I really have no idea what's going on.

P.S. I'm really a big fan of your work!

**Comment by LekoArts** [comment]
Some React versions mismatched, should work now again.
