### ISSUE TITLE
Cannot see any source code

### ISSUE THREAD

**Issue by farmanp** [LekoArts/gatsby-starter-portfolio-cara#120]
I can't see any src other than the index.mdx, am I missing something here? New to GatsbyJS

**Comment by LekoArts** [comment]
This starter uses my Gatsby theme: https://github.com/LekoArts/gatsby-themes/tree/master/themes/gatsby-theme-cara

You can learn more about Gatsby themes here 👍 	
https://github.com/LekoArts/gatsby-themes#-learning-gatsby-themes
