### ISSUE TITLE
how to remove this black line ?

### ISSUE THREAD

**Issue by lili21** [LekoArts/gatsby-starter-portfolio-cara#13]
![image](https://user-images.githubusercontent.com/4456380/50337319-afb3e800-054b-11e9-9821-d8b83d5368b8.png)

when I scroll the page, the line will flash. is it a bug ?

**Comment by lili21** [comment]
I think there is a gap. and the color is the background-color of html, make it looks like a line.

**Comment by LekoArts** [comment]
There can't be a gap, it's one solid background, hence the issue you're seeing doesn't make sense 🤔 I also don't see that issue on any browser. What browser are you using?

**Comment by lili21** [comment]
I'm using Chrome 71.0.3578.98. Those gap will disappear If I remove [this line](https://github.com/LekoArts/gatsby-starter-portfolio-cara/blob/master/src/pages/index.jsx#L27)

**Comment by spencec6** [comment]
I have the same issue 🙋‍♂️ Chrome 71.0.3578.98.

**Comment by ARXChrono** [comment]
Can confirm this is an issue, only on MacOS with Google chrome.

**Comment by elijahio** [comment]
Has anyone found a solution to this issue (@ARXChrono, @spencec6, or @lili21)?

I tried removing the line you linked to, @lili21, but that's not the solution (I even went back to see if it referenced a different line at the time of the issue).

I also tried that SO suggestion to no avail.

**Comment by elijahio** [comment]
Not a perfect fix, but if you remove line 14 (speed={-0.2}), it fixed this issue. Indeed it is just Chrome on Mac OS.
