### ISSUE TITLE
Updating Typefaces

### ISSUE THREAD

**Issue by spencec6** [LekoArts/gatsby-starter-portfolio-cara#14]
I can't for the life of me figure out what is going on here. I've read through [tailwind's documentation](https://tailwindcss.com/docs/configuration/), I've read through [Kyle Matthew's Typefaces documentation](https://github.com/KyleAMathews/typefaces), and as far as I know, I've followed the steps exactly, but no matter what, my Subtitle's font-family stays the same:
![image](https://user-images.githubusercontent.com/9611917/50379630-e9e4be80-060b-11e9-82a1-9a438e16cf7b.png)

- [x] I'm running `gatsby develop`.

- [x] I've installed a new typeface, "PT-Sans" in this case, by running `npm install --save typeface-pt-sans` as directed in the package readme.

- [x] I've replaced Open Sans with "Pt Sans" in the fonts object in the tailwind.js config file:
![image](https://user-images.githubusercontent.com/9611917/50379655-742d2280-060c-11e9-897f-a547da8806dc.png)

- [x] I've imported the module in my index.jsx:
![image](https://user-images.githubusercontent.com/9611917/50379659-8f982d80-060c-11e9-83e5-cb3bb7bba864.png)

But no matter what, any instance of ${tw(font-sans)} continually shows with the font-family value as shown above. Is there another command I need to run in order to update the `tailwind.js` file? I've tried  adjusting color hex values to see if that works, and it looks like that is also not updating. Any help you can offer is greatly appreciated, this is driving me crazy!

**Comment by LekoArts** [comment]
Try deleting the `tailwind.custom.css` file and re-run the develop/build command. Then a new _custom_ file will be generated.

**Comment by LekoArts** [comment]
Should be solved now with https://github.com/LekoArts/gatsby-starter-portfolio-cara/pull/15
