### ISSUE TITLE
Custom tailwind css

### ISSUE THREAD

**Issue by muhajirframe** [LeKoArts/gatsby-starter-portfolio-cara#2]
Hi @LeKoArts , Thanks for the beautiful work.

I was trying to custom `tailwind.js`, added `'40': '10 rem'`.
But when I tried to use it with `px-40`. It doesn't work. Do you have any idea why?

Step to reproduce:
1. Modify `tailwind.js`'s padding. 
From 
```javascript
 padding: {
    px: '1px',
    '0': '0',
    '1': '0.25rem',
    '2': '0.5rem',
    '3': '0.75rem',
    '4': '1rem',
    '6': '1.5rem',
    '8': '2rem',
    '12': '3rem',
    '16': '4rem',
    '24': '6rem',
    '32': '8rem',
  },
```
to 
```javascript
 padding: {
    px: '1px',
    '0': '0',
    '1': '0.25rem',
    '2': '0.5rem',
    '3': '0.75rem',
    '4': '1rem',
    '6': '1.5rem',
    '8': '2rem',
    '12': '3rem',
    '16': '4rem',
    '24': '6rem',
    '32': '8rem',
    '40': '10rem',
  },
```
2. Use `px-40` somewhere in the code.

I also tried to modify `'32': '1rem'`. It seems to have no effect

**Comment by muhajirframe** [comment]
Never mind, it works now. I don't know why. I just tried to remove `node_modules/` and `public/`.

**Comment by LeKoArts** [comment]
You have to rebuild the css if you change things. That happens when you start the dev server / run a build. Maybe that was the issue

**Comment by LeKoArts** [comment]
You shouldn't need to remove `node_modules`. If a restart of the dev server doesn't help you can delete the `tailwind.custom.css`
