### ISSUE TITLE
Images are not displaying at first time.

### ISSUE THREAD

**Issue by arjun-kava** [LekoArts/gatsby-starter-portfolio-cara#6]
First of all, Thank you for sharing such a great starter.

I think images are not loading first time using due to some issue. I have checked the original demo. It has the same issue.

paste https://portfolio-cara.netlify.com/ on URL bar and press enter, avtar.jpg will not display until you refresh page.

**Comment by diplozoon** [comment]
I'm using this starter and encountered same issue.

**Comment by LekoArts** [comment]
I pushed https://github.com/LekoArts/gatsby-starter-portfolio-cara/commit/545c6f69311d703246032e74eccf5dfb80efa20d up the repo. Changing the height from `100%` to `auto` on the avatar. I didn't encounter the issue anymore. Can you confirm?

**Comment by diplozoon** [comment]
LGTM

**Comment by arjun-kava** [comment]
It seems resolved. Thank you for the quick response. Have a great day.
