### ISSUE TITLE
`npm install` fails on install

### ISSUE THREAD

**Issue by elijahio** [LekoArts/gatsby-starter-portfolio-cara#62]
**Steps to reproduce:**

1. Run `gatsby new new-site https://github.com/LekoArts/gatsby-starter-portfolio-cara`

**Error:**

- Error: Command failed: npm install

**I've tried:**

- Removing `node-gyp` file and running `npm update` as per https://github.com/nodejs/node-gyp/issues/809
- Running `npm audit fix --force` as per https://github.com/nodejs/node-gyp/issues/809

**Node version:**

- v12.0.0

**Comment by LekoArts** [comment]
Please try Node v10 or v11

**Comment by elijahio** [comment]
Sorry for the trouble, @LekoArts – that worked.

**Steps to fix:**

1. Use Node v11 (11.0.0 worked for me).

_I downgraded Node using https://www.npmjs.com/package/n_

-
