### ISSUE TITLE
Adjusting divider height

### ISSUE THREAD

**Issue by sagardesai90** [LekoArts/gatsby-starter-portfolio-cara#7]
I was interested in reducing the space in between sections. Notably, index.jsx has a method that allowed me to set the number of dividers, but not the height. Would love to hear back on what may work.

Thanks!

**Comment by LekoArts** [comment]
You adjust that via the props on the divider: https://react-spring.surge.sh/parallax

Sections with a factor of 2 are double the size for example. The offset sets the position in the hierarchy

**Comment by sagardesai90** [comment]
Was able to figure it out, thank you!

**Comment by LekoArts** [comment]
Cool! 👍
