### ISSUE TITLE
Error on pushing to github

### ISSUE THREAD

**Issue by McSteve7** [LekoArts/gatsby-starter-portfolio-cara#71]
I get the error below whenever I push to GitHub even after changing the Repo's URL in the package.json
```
remote: Permission to LekoArts/gatsby-starter-portfolio-cara.git denied to McSteve7.
fatal: unable to access 'https://github.com/LekoArts/gatsby-starter-portfolio-cara/': The requested URL returned error: 403
```

**Comment by boggsey** [comment]
This isn't an issue with this project. Instead, you need to change your origin to reflect a repository that you own.

- You can view your repos origin by navigating to your projects root folder in the command line and typing `git remote -v`.
- You can change the url by typing `git remote set-url origin https://github.com/USERNAME/REPOSITORY.git` - where USERNAME and REPOSITORY are changed to reflect your project's specific details.

More info here: https://help.github.com/en/articles/changing-a-remotes-url

**Comment by McSteve7** [comment]
Thank you. I was able to fix it!

Regards.
