### ISSUE TITLE
Firefox produces warning "Will-change memory consumption too high"

### ISSUE THREAD

**Issue by avinoamsn** [LekoArts/gatsby-starter-portfolio-cara#94]
Warning produced in Firefox 67:
Will-change memory consumption is too high. Budget limit is the document surface area multiplied by 3 (960614 px). Occurrences of will-change over the budget will be ignored.

I assume this has something to do with the way the project is bundled. Do you have any suggestions for optimizing will-change usage?

**Comment by LekoArts** [comment]
Please open an issue on the react-spring repo (as this project uses this): https://github.com/react-spring/react-spring

The starter doesn't use the "will-change" property. Thanks!
